### ISSUE TITLE
柳志超、方杰两位朋友的blog链接地址有问题,望更正

### ISSUE THREAD

**Issue by shuaisunny** [chaojimiaomiao/androidBlogCN#2]
🐱🐱 
**[柳志超博客](https://liuzhichao.com/)**
**[方杰](http://blog.fangjie.info/)**
两位朋友的blog链接地址有问题，望更正。

**Comment by chaojimiaomiao** [comment]
非常感谢，我已经修正了！在这个commit里： https://github.com/chaojimiaomiao/androidBlogCN/commit/2d91a9cb2a629ed9fcc53a290e22213cfdf1af74
